wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715904085.747805
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 5
      - 14
      - 23
      4: 3.11.3
      5: 0.15.0
      8:
      - 5
Model:
  desc: null
  value:
    dropout: 0.1
    in_size: 5
    hid_size: 64
    n_layers: 2
    out_size: 1
Training:
  desc: null
  value:
    epochs: 10
    batch_size: 10000
    learning_rate: 0.0001
base_config:
  desc: null
  value: testcfg.yaml
full_config:
  desc: null
  value:
    Model:
      args:
        dropout: 0.1
        in_size: 5
        hid_size: 64
        n_layers: 2
        out_size: 1
      class: MLP
      module: memes_base.models
    Dataset:
      args:
        name: test_dataset
        save: true
        chunks: 1
        raw_file: fake_data.csv
        save_dir: dataset_saves/dummy_dataset_chunked
      class: DummyDataset
      module: memes_base.datasets
    Training:
      epochs: 10
      batch_size: 10000
      learning_rate: 0.0001
    Training_Directory: model_saves/dummy_model/run_i8dh403g/
