wandb_version: 1

Training:
  desc: null
  value:
    batch_size: 256
    learning_rate: 0.0001
    epochs: 10
Model:
  desc: null
  value:
    in_size: 5
    hid_size: 10000
    out_size: 1
    n_layers: 4
    dropout: 0.1
base_config:
  desc: null
  value: testcfg.yaml
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715892260.856069
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.0
      8:
      - 5
full_config:
  desc: null
  value:
    Training_Directory: model_saves/dummy_model/run_ju4mcifx/
    Model:
      module: memes_base.models
      class: MLP
      args:
        in_size: 5
        hid_size: 10000
        out_size: 1
        n_layers: 4
        dropout: 0.1
    Training:
      batch_size: 256
      learning_rate: 0.0001
      epochs: 10
    Dataset:
      module: memes_base.datasets
      class: DummyDataset
      args:
        name: test_dataset
        raw_file: fake_data.csv
        save_dir: dataset_saves/dummy_dataset_chunked
        save: true
        chunks: 1
